### ISSUE TITLE
Entradas y salidas del microcontrolador

### ISSUE THREAD

**Issue by jemmanuelhv94** [jemmanuelhv94/DSE_Motor_Control_E7#2]
- [x]  Crear en excel Lista de entradas y salidas

**Comment by msamuelpf** [comment]
Para cerrarlo deben documentar en excel por ejemplo y compartir el archivo...

**Comment by jemmanuelhv94** [comment]
[CESEQ_E7_IOs.xlsx](https://github.com/jemmanuelhv94/DSE_Motor_Control_E7/files/2839024/CESEQ_E7_IOs.xlsx)

**Comment by jemmanuelhv94** [comment]
[CESEQ_E7_IOs.xlsx](https://github.com/jemmanuelhv94/DSE_Motor_Control_E7/files/2839229/CESEQ_E7_IOs.xlsx)
