### ISSUE TITLE
Entradas y salidas del motor DC

### ISSUE THREAD

**Issue by jemmanuelhv94** [jemmanuelhv94/DSE_Motor_Control_E7#4]
- [ ] Investigar y documentar en un archivo de word el funcionamiento del motor (Entradas de potencia, sensado de RPM, etc.)
- [ ] Crear diagrama de conexión (Esquemático)
- [ ] Crear en excel lista de pines de MCU a Motor DC

**Comment by ManeCR** [comment]
Se anexa documento con las entradas y salidas de motor y sensor hall

[Entradas y salidas motor +sensor hall.xlsx.pdf](https://github.com/jemmanuelhv94/DSE_Motor_Control_E7/files/2969354/Entradas.y.salidas.motor.%2Bsensor.hall.xlsx.pdf)
